version: '3.8'
services:
  app:
    build:
      context: .  
      dockerfile: Dockerfile  
    image: apimongoose
    container_name: node-app
    ports:
      - "3000:3000"
    command: npm start


