name: Node.js CI with Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build and run app with Docker Compose
        run: docker-compose up -d --build

      - name: Wait for the app to be ready
        run: sleep 10

      - name: Test web1
        run: curl --fail http://localhost:3000/web1

      - name: Test web2
        run: curl --fail http://localhost:3000/web2

      - name: Shut down Docker containers
        run: docker-compose down


